### ISSUE TITLE
Doesn't switch focused border to other floating window

### ISSUE THREAD

**Issue by cHoco** [koekeishiya/kwm#293]
When I have focused a floating window, clicking on another floating window doesn't update the focused border.

**Comment by cHoco** [comment]
There's still a small issue, if I have focused a floating window and I open a new window (same app or other), which should float, the focused border isn't updated.

**Comment by cHoco** [comment]
The change is also drawing the focused border for full screen apps, so you should probably add a check for the space before calling KwmFocus

**Comment by koekeishiya** [comment]
> The change is also drawing the focused border for full screen apps, so you should probably add a check for the space before calling KwmFocus 

Fullscreen as in OSX fullscreen mode? I'm unable to reproduce that.

**Comment by cHoco** [comment]
Yep, it is indeed difficult to see because only the edges are visible, but if you add a DEBUG right before `UpdateBorder` in the `SetKwmFocus` function you can see that it is being updated.

**Comment by koekeishiya** [comment]
> so you should probably add a check for the space before calling KwmFocus 

Doing this made no difference, not completely sure what's going on there.

**Comment by koekeishiya** [comment]
> There's still a small issue, if I have focused a floating window and I open a new window (same app or other), which should float, the focused border isn't updated. 

Should be fixed for same app now. I tried a couple of things to make it also behave properly for new applications, but this caused other issues that I do not know how to resolve.

> The change is also drawing the focused border for full screen apps, so you should probably add a check for the space before calling KwmFocus 

I believe this should also be fixed now (no idea what causes it if it is still there).

**Comment by cHoco** [comment]
> Should be fixed for same app now. I tried a couple of things to make it also behave properly for new applications, but this caused other issues that I do not know how to resolve.

It doesn't seem to work for me :(

> I believe this should also be fixed now (no idea what causes it if it is still there).

It still happens for me :( but this diff fixes it in my setup.

``` diff
diff --git a/kwm/workspace.mm b/kwm/workspace.mm
index b0f378c..ced91e3 100644
--- a/kwm/workspace.mm
+++ b/kwm/workspace.mm
@@ -83,7 +83,8 @@ extern kwm_thread KWMThread;
                         if(!SameScreen)
                             GiveFocusToScreen(OSXScreen->ID, NULL, false, false);
 
-                        SetKwmFocus(OSXWindowRef);
+                        if(OSXSpace->Managed)
+                            SetKwmFocus(OSXWindowRef);
                         if(SameScreen && !Floating)
                             KWMFocus.InsertionPoint = KWMFocus.Cache;
                     }
```

**Comment by koekeishiya** [comment]
That is reall weird. I did try that earlier and it had no effect for me. I'll add it in there tho if it does make a change for others.
