### ISSUE TITLE
Rule floated application does not trigger standby-on-float on first focus

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#299]
Steps to Reproduce

1. Add an application rule with floating
```
kwmc rule owner="System Preferences" properties={float="true"}
```
2. Open application
3. Observe application is focused with out border and `standby-on-float` not engaged. 

Expected Results

Rule floated application to have border and to disable `focus-follows-mouse` when `standby-on-float` is enabled.

**Comment by koekeishiya** [comment]
This is not a problem with `standby-on-float` or `float` unfortunately. This issue is from what I've tried so far not fixable without it breaking `cmd+tab` support in some way or another.

The core issue for the above behaviour is that `SetKwmFocus` does not get called at all.

**Comment by chrishoage** [comment]
`cmd+tab` is way more important in my opinion so best not to break that. 

I'm sure there is more to this than I understand, but I'm curious is there any application / window launch notification that does get triggered, just not a focus notification? Or is no notification given in this situation and kwm doesn't "see" it at all?

**Comment by koekeishiya** [comment]
> I'm sure there is more to this than I understand, but I'm curious is there any application / window launch notification that does get triggered, just not a focus notification? Or is no notification given in this situation and kwm doesn't "see" it at all? 

The only notification that is triggered that Kwm currently detects is `didActivateApplication()@workspace.mm`, which is the same one triggered by `cmd+tab` and all other instances where an application gains focus for the first time.

I believe there is also an `didLaunchApplication` notification that could possibly be used to fix the above issue.

**Comment by koekeishiya** [comment]
The `didLaunchApplicationNotification` seems to have fixed it. Not sure if this broke some multi-monitor tiling when opening new applications though.

**Comment by chrishoage** [comment]
Odd, it works _sometimes_, but still has the old behavior much of the time. 

Not a huge deal to me. Just odd that it intermittently works now.

**Comment by koekeishiya** [comment]
>  but still has the old behavior much of the time. 

This is probably for application thats do not quit after all their windows have been closed. Thus, they will not be sending `launchApplicaitonNotifications`.

Not much I can do about this for now, maybe I'll find some creative way of doing it in the future.

**Comment by chrishoage** [comment]
> This is probably for application thats do not quit after all their windows have been closed.

To be clear this is how I was testing it: 

`cmd + Q` application
Launch application

It makes no difference how the Application was launched: Alfred, the Dock. 

I tried with System Preferences, VLC, QuickTime. All of them starting from a "Quit" state (using `cmd + Q`) then opening again. 

So I guess this is more nuanced than I thought.

**Comment by cHoco** [comment]
Today I got sometime to look at this and I think I figured what the issue is. Basically when an application is launched we get the notification correctly in `workspace.mm`, that in turn calls `FocusWindowOfOSX()`.

`FocusWindowOfOSX()` correctly identifies through the accessibility api the window that it should focus, and call `SetKwmFocus()`. In this function kwm tries to obtain the `window_info*` for the `AXUIElementRef` but since the new window is NOT included in the window list the first check `    if(WindowsAreEqual(&KWMFocus.Cache, &KWMFocus.NULLWindowInfo))` fails and the issue described above unfolds.
The solution should be rather simple, calling `UpdateWindowTree()` before calling `FocusWindowOfOSX()`, but unfortunately the CG API that `UpdateActiveWindows()`uses takes some time to update, and doesn't report the new window when called just after the notification :(
So to solve this, we either:

1. add the window manually (instead of calling `UpdateWindwoTree()`) through information received by the accessibility API
2. change UpdateActiveWindow() to obtain windows using accessibility API or at least a mixture of them.
3. wait some time before calling `FocusWindowOfOSX()` in `workspace.mm`

**Comment by koekeishiya** [comment]
> change UpdateActiveWindow() to obtain windows using accessibility API or at least a mixture of them.

This will break focus-follows-mouse support. The API in use is the reason we get proper z-ordering.

**Comment by cHoco** [comment]
Yeah, I know, that's why I mentioned a mixture but it would anyway require a major refactoring. The third one is the easiest, and the one I'm using because it didn't have lots of time, but it's more an hack thank a solution. 
``` diff
diff --git a/kwm/workspace.mm b/kwm/workspace.mm
index 4209d3e..18e116b 100644
--- a/kwm/workspace.mm
+++ b/kwm/workspace.mm
@@ -3,6 +3,7 @@
 #include "notifications.h"
 
 extern void UpdateActiveSpace();
+extern void UpdateWindowTree();
 extern screen_info *GetDisplayOfWindow(window_info *Window);
 extern bool GetWindowFocusedByOSX(AXUIElementRef *WindowRef);
 extern void SetKwmFocus(AXUIElementRef WindowRef);
@@ -64,6 +65,8 @@ extern kwm_thread KWMThread;
 
 - (void)didLaunchApplication:(NSNotification *)notification
 {
+    usleep(200000);
+    UpdateWindowTree();
     FocusWindowOfOSX();
 }
 
```
The first solution would probably be the best one.

**Comment by koekeishiya** [comment]
> but it would anyway require a major refactoring.

The entire codebase really needs a major refactoring and there needs to be established a clear internal API. I'm not sure when I will start working on Kwm again, as I'm busy with finals.

**Comment by koekeishiya** [comment]
This should be fixed in latest version.

**Comment by sxmichaels** [comment]
Running kwm 3.0.1, this works for System Preferences as in the original example, but the iTerm2 hotkey window (which I mentioned in the duplicate #363) still doesn't get the border when it opens. I have the following rule in my `kwmrc`:

```
kwmc rule owner="iTerm2Visor" properties={role="AXDialog",float=true}
```

(iTerm2Visor is just a separate application with a different bundle name and identifier so I can open a visor window without focusing other iTerm windows, but it is otherwise identical to iTerm2.)

**Comment by koekeishiya** [comment]
> kwmc rule owner="iTerm2Visor" properties={role="AXDialog",float=true}

Should be: `kwmc rule owner="iTerm2Visor" properties={role="AXDialog";float=true}`

**Comment by sxmichaels** [comment]
Ah, oops. That was definitely part of the problem. Changing to a semicolon, however, it seems that the `float=true` option doesn't have any effect on my iTermVisor app — which I remembered is actually different in one other significant way, and I think this is the problem. Regular iTerm2 with the visor option _does_ work as expected, however, in the plist of iTermVisor, I've set LSUIElement=1 ("Application is Agent"=YES). This prevents the visor from retaining focus when I close it via the hotkey, but it also makes the application not fully focus even when I am typing into it, e.g. the statusbar still shows the menus for the program I had focused before I opened the visor. My guess is that that flag also prevents the regular "focus change" hook from being called, so perhaps this has a different root cause than the @chrishoage's original issue.

If you want me to run some sort of diagnostic / monitoring tool to check what notifications are sent, just tell me what to use I'll do so.

Here is my [visor-modified iTerm app](https://github.com/koekeishiya/kwm/files/348582/iTermVisor.app.zip), by the way.
