### ISSUE TITLE
Send window to display breaks changing display foucs

### ISSUE THREAD

**Issue by chrishoage** [koekeishiya/kwm#324]
Steps to reproduce: 

1. Send a window to another display `window -m display 1`
2. Attempt to change focus back to previous screen `display -f prev`

Expected result: Previous screen to be focused. 

Actual result: No screen focus change is possible until the mouse is used to give focus to the previous display.

**Comment by koekeishiya** [comment]
Not sure if I understood what this issue is about, but `window -fm prev` is only to be used between monocle windows inside of a bsp-node.

**Comment by chrishoage** [comment]
I had a copy paste error, I updated the OP to include the correct command. The email still had the incorrect command.

**Comment by koekeishiya** [comment]
Will check when I get home later tonight.

**Comment by koekeishiya** [comment]
Do you happen to know if this is also broken in Kwm version 2.0.3 as well, or just on master?

**Comment by chrishoage** [comment]
Moving the window only is fine, the issue I am having is that `display -f` does _nothing_ until I use the mouse to focus a display. 

The issue is that `display -f` seems to be broken completely after moving a window.

**Comment by koekeishiya** [comment]
Fixed in latest commit.

I let the behaviour remain as is.
Moving a window will also move focus to the new display.

**Comment by chrishoage** [comment]
👍 this behavior seems more predicable. Confirmed working.

**Comment by chrishoage** [comment]
Ok, this isn't quite fixed. 

Oddly enough doing `window -m 2` works. I can use `display -f`. 

However, going back the other way `window -m 1` exhibits the same behavior as before. 

`GiveFocusToScreen` appears to be called, but focus is not updated with kwm. It _is_ updated with osx. When it is in this state using kwm focus commands do not work.

**Comment by koekeishiya** [comment]
Well this is weird, works fine for me.

**Comment by chrishoage** [comment]
I just tried again, here are my steps:

1. Send focused window to 2nd display `window -m display 1`
2. Focus previous display `display -f prev` 
3. Focus previous display `display -f prev`
4. Send focused window back to 1st display `window -m display 0`
5. Focus previous display `display -f prev`

OS X focus the previous display, but the kwm focus does not update. Kwm still receives commands but doesn't change state

```
Local Daemon is now running..
DisplayID 441231622 has index 0
DisplayID 69733314 has index 1
CreateWindowNodeTree() Create Space 3
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
KwmExecuteHotkey
GiveFocusToScreen() 1: Space transition ended 3 -> 119
Uninitialized Screen
CreateWindowNodeTree() Create Space 119
SetWindowDimensions() Update window dimensions
SetWindowRefFocus() Focused Window: Slack 3860,1198
KwmExecuteHotkey
GiveFocusToScreen() 0: Space transition ended 119 -> 3
Populated Screen Key/Mouse Focus
SetWindowRefFocus() Focused Window: kwm 22,45
KwmExecuteHotkey
SetWindowRefFocus() Focused Window: react-router/API.md at master · reactjs/react-router 20,1077
KwmExecuteHotkey
RemoveWindowFromBSPTree() Parent && LeftChild && RightChild
SetWindowDimensions() Update window dimensions
AddWindowToTreeOfUnfocusedMonitor() Monocle Space
SetWindowDimensions() Update window dimensions
SetWindowRefFocus() Focused Window: react-router/API.md at master · reactjs/react-router 3860,1198
SetWindowDimensions() Update window dimensions
KwmExecuteHotkey
GiveFocusToScreen() 0: Space transition ended 119 -> 3
Populated Screen Key/Mouse Focus
SetWindowRefFocus() Focused Window: kwm 22,45
KwmExecuteHotkey
GiveFocusToScreen() 1: Space transition ended 3 -> 119
Populated Screen Key/Mouse Focus
SetWindowRefFocus() Focused Window: react-router/API.md at master · reactjs/react-router 3860,1198
KwmExecuteHotkey
AddWindowToTreeOfUnfocusedMonitor() BSP Space
SetWindowDimensions() Update window dimensions
SetWindowDimensions() Update window dimensions
SetWindowRefFocus() Focused Window: react-router/API.md at master · reactjs/react-router 20,558
SetWindowDimensions() Update window dimensions
KwmExecuteHotkey
###
###
### This is where focus gets lost. Notice how the screen transition takes place but no SetWindowRefFocus
###
###
GiveFocusToScreen() 1: Space transition ended 3 -> 119
Populated Screen Key/Mouse Focus
KwmExecuteHotkey
KwmExecuteHotkey
KwmExecuteHotkey
KwmExecuteHotkey
GiveFocusToScreen() 0: Space transition ended 119 -> 3
Populated Screen Key/Mouse Focus
SetWindowRefFocus() Focused Window: react-router/API.md at master · reactjs/react-router 20,558
KwmExecuteHotkey
SetWindowRefFocus() Focused Window: kwm 22,42
```

**Comment by koekeishiya** [comment]
I am only able to reproduce the above behaviour if the space of the display that I am moving a window to has not been initialized.

If you start Kwm, give focus to each if the displays either through binds or using the mouse, the above should not be reproducible.

**Comment by chrishoage** [comment]
```
Local Daemon is now running..
Creating display with:
ID: 441231622Resolution: 3840x2160 Origin: (0,0)
DisplayID 441231622 has index 0 and ID 4268EF99-6620-8CD4-A0E6-EFD08D4D5365
Creating display with:
ID: 69733314Resolution: 1920x1200 Origin: (3840,1158)
DisplayID 69733314 has index 1 and ID 1FBF2F7F-57EC-56E5-521F-556A305D1A61
CreateWindowNodeTree() Create Space 3
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
SetWindowDimensions() zsh pos: 20,45 size: 1889,1011
SetWindowDimensions() zsh pos: 20,1082 size: 1889,1011
SetWindowDimensions() Send window to display breaks changing display foucs · Issue #324 · koekeishiya/kwm pos: 1930,40 size: 1890,2055
SetWindowDimensions() zsh pos: 20,45 size: 1889,1011
KwmExecuteHotkey
DISPLAY ACTIVE
GiveFocusToScreen() 1: Space transition ended 3 -> 145
Uninitialized Screen
CreateWindowNodeTree() Create Space 145
SetWindowDimensions() Slack pos: 3860,1198 size: 1880,1095
SetWindowDimensions()  pos: 3860,1198 size: 1880,1095
SetWindowDimensions() node pos: 3862,1202 size: 1877,1090
SetWindowRefFocus() Focused Window: Slack 3860,1198
KwmExecuteHotkey
DISPLAY ACTIVE
GiveFocusToScreen() 0: Space transition ended 145 -> 3
Populated Screen Key/Mouse Focus
SetWindowRefFocus() Focused Window: kwm 20,45
KwmExecuteHotkey
DISPLAY ACTIVE
GiveFocusToScreen() 1: Space transition ended 3 -> 145
Populated Screen Key/Mouse Focus
SetWindowRefFocus() Focused Window: Slack 3860,1198
KwmExecuteHotkey
SetWindowFocusByNode()
SetWindowRefFocus() Focused Window: node 3862,1202
KwmExecuteHotkey
AddWindowToTreeOfUnfocusedMonitor() BSP Space
SetWindowDimensions() kwm pos: 22,45 size: 932,1011
SetWindowDimensions() node pos: 977,45 size: 932,1011
DISPLAY ACTIVE
GiveFocusToScreen() 0: Space transition ended 145 -> 3
SetWindowRefFocus() Focused Window: node 977,45
SetWindowDimensions() node pos: 977,45 size: 932,1011
KwmExecuteHotkey
DISPLAY ACTIVE
GiveFocusToScreen() 1: Space transition ended 3 -> 145
Populated Screen Key/Mouse Focus
KwmExecuteHotkey
KwmExecuteHotkey
KwmExecuteHotkey
DISPLAY ACTIVE
GiveFocusToScreen() 0: Space transition ended 145 -> 3
Populated Screen Key/Mouse Focus
SetWindowRefFocus() Focused Window: node 977,45
KwmExecuteHotkey
SetWindowRefFocus() Focused Window: kwm 22,45
```

I can still reproduce this. 

Notice in the logs I have initialized both screens before attempting the steps I posted previously.

**Comment by koekeishiya** [comment]
I noticed you are runing with the `GPU patch` from @cHoco. I have no idea what this patch currently does and how it may affect the changes I've done to master regarding this issue.

**Comment by chrishoage** [comment]
Ah, good catch. Let me revert that and try again.

**Comment by chrishoage** [comment]
Ok, `git reset --hard` and re-ran make. Same result unfortunately 

```
Local Daemon is now running..
DisplayID 441231622 has index 0
DisplayID 69733314 has index 1
CreateWindowNodeTree() Create Space 3
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
SetWindowDimensions() zsh pos: 20,45 size: 1889,1011
SetWindowDimensions() Better support for dual GPUs setups · Issue #323 · koekeishiya/kwm pos: 20,1077 size: 1890,1017
SetWindowDimensions() display-log.txt pos: 1930,40 size: 1890,2055
SetWindowRefFocus() Focused Window: Better support for dual GPUs setups · Issue #323 · koekeishiya/kwm 20,1077
SetWindowDimensions() Better support for dual GPUs setups · Issue #323 · koekeishiya/kwm pos: 20,1077 size: 1890,1017
SetWindowDimensions() Better support for dual GPUs setups · Issue #323 · koekeishiya/kwm pos: 20,1077 size: 1890,1017
KwmExecuteHotkey
GiveFocusToScreen() 1: Space transition ended 3 -> 149
Uninitialized Screen
CreateWindowNodeTree() Create Space 149
SetWindowDimensions() node pos: 3862,1202 size: 1877,1090
SetWindowDimensions() Slack pos: 3860,1198 size: 1880,1095
SetWindowDimensions() zsh pos: 3862,1202 size: 1877,1090
SetWindowRefFocus() Focused Window: node 3862,1202
KwmExecuteHotkey
GiveFocusToScreen() 0: Space transition ended 149 -> 3
Populated Screen Key/Mouse Focus
SetWindowRefFocus() Focused Window: Better support for dual GPUs setups · Issue #323 · koekeishiya/kwm 20,1077
KwmExecuteHotkey
GiveFocusToScreen() 1: Space transition ended 3 -> 149
Populated Screen Key/Mouse Focus
SetWindowRefFocus() Focused Window: node 3862,1202
KwmExecuteHotkey
AddWindowToTreeOfUnfocusedMonitor() BSP Space
SetWindowDimensions() kwm pos: 22,45 size: 932,1011
SetWindowDimensions() node pos: 977,45 size: 932,1011
GiveFocusToScreen() 0: Space transition ended 149 -> 3
SetWindowRefFocus() Focused Window: node 977,45
SetWindowDimensions() node pos: 977,45 size: 932,1011
KwmExecuteHotkey
GiveFocusToScreen() 1: Space transition ended 3 -> 149
Populated Screen Key/Mouse Focus
KwmExecuteHotkey
KwmExecuteHotkey
KwmExecuteHotkey
KwmExecuteHotkey
KwmExecuteHotkey
KwmExecuteHotkey
KwmExecuteHotkey
KwmExecuteHotkey
KwmExecuteHotkey
KwmExecuteHotkey
GiveFocusToScreen() 0: Space transition ended 149 -> 3
Populated Screen Key/Mouse Focus
SetWindowRefFocus() Focused Window: node 977,45
KwmExecuteHotkey
SetWindowRefFocus() Focused Window: kwm 22,45
```

**Comment by koekeishiya** [comment]
I did  the following steps just now:
```
    Send focused window to 2nd display window -m display 1
    Focus previous display display -f prev
    Focus previous display display -f prev
    Send focused window back to 1st display window -m display 0
    Focus previous display display -f prev
```

Everything works perfectly for me. Does any of your displays override default mode / padding / gaps in the kwmrc file? All my displays are set to `bsp`. Maybe this could be some `monocle` mode only issue?

**Comment by chrishoage** [comment]
Ah! Yes I do have Display 1 set to `monocle` mode. I will test this with both set to BSP, give me a few minutes.

**Comment by chrishoage** [comment]
@koekeishiya Very good catch! It _only_ happens when going from a BSP space to a Monocle space. It works perfectly BSP -> BSP!

**Comment by koekeishiya** [comment]
Right, so I'm able to reproduce now. Will work on a fix in a bit.

**Comment by koekeishiya** [comment]
Should be fixed for sure this time.

**Comment by chrishoage** [comment]
Yup! it is fixed. 

Odd behavior though: 

1. Send window to display that is in monocle mode `window -m display 1`
2. Start cycling though windows `window -f east`
3. After about 2 or 3 cycles the original display becomes focused again for some reason

This behavior only happens when the space the window is sent to is in Monocle mode. If the space is in BSP mode cycling though the windows will always stay on that display.

**Comment by koekeishiya** [comment]
> This behavior only happens when the space the window is sent to is in Monocle mode. If the space is in BSP mode cycling though the windows will always stay on that display. 

Hmm, I'm unable to reproduce this..awkward

**Comment by chrishoage** [comment]
```
Local Daemon is now running..
DisplayID 441231622 has index 0
DisplayID 69733314 has index 1
CreateWindowNodeTree() Create Space 3
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
CreateBSPTree() Create pair of leafs
SetWindowDimensions() zsh pos: 22,45 size: 932,1011
SetWindowDimensions() Send window to display breaks changing display foucs · Issue #324 · koekeishiya/kwm pos: 975,40 size: 935,1017
SetWindowDimensions() kwmrc pos: 20,1077 size: 1890,1017
SetWindowDimensions() zsh pos: 1930,45 size: 1889,1011
SetWindowDimensions() zsh pos: 1930,1082 size: 1889,1011
SetWindowDimensions() zsh pos: 22,45 size: 932,1011
KwmExecuteHotkey
GiveFocusToScreen() 1: Space transition ended 3 -> 176
Uninitialized Screen
CreateWindowNodeTree() Create Space 176
SetWindowDimensions() Slack pos: 3860,1198 size: 1880,1095
SetWindowRefFocus() Focused Window: Slack 3860,1198
KwmExecuteHotkey
GiveFocusToScreen() 0: Space transition ended 176 -> 3
Populated Screen Key/Mouse Focus
SetWindowRefFocus() Focused Window: kwm-overlay 22,45
KwmExecuteHotkey
SetWindowRefFocus() Focused Window: Send window to display breaks changing display foucs · Issue #324 · koekeishiya/kwm 975,40
KwmExecuteHotkey
SetWindowRefFocus() Focused Window: zsh 1930,45
KwmExecuteHotkey
RemoveWindowFromBSPTree() Parent && LeftChild && RightChild
SetWindowDimensions() zsh pos: 1930,44 size: 1889,2050
AddWindowToTreeOfUnfocusedMonitor() Monocle Space
SetWindowDimensions() zsh pos: 3862,1202 size: 1877,1090
GiveFocusToScreen() 1: Space transition ended 3 -> 176
SetWindowRefFocus() Focused Window: zsh 3862,1202
SetWindowDimensions() zsh pos: 3862,1202 size: 1877,1090
KwmExecuteHotkey
SetWindowFocusByNode()
SetWindowRefFocus() Focused Window: Slack 3860,1198
KwmExecuteHotkey
SetWindowFocusByNode()
SetWindowRefFocus() Focused Window: zsh 3862,1202
GiveFocusToScreen() 0: Space transition ended 176 -> 3
KwmExecuteHotkey
SetWindowRefFocus() Focused Window: Send window to display breaks changing display foucs · Issue #324 · koekeishiya/kwm 975,40
SetWindowRefFocus() Focused Window: kwm-overlay 22,45
```

Probably not helpful but here are my logs.

**Comment by koekeishiya** [comment]
If you can reliably reproduce this odd behaviour, could you create a new issue for it and list steps to reproduce etc?

**Comment by chrishoage** [comment]
Moved to #328
