### ISSUE TITLE
Youtube fullscreen freezes Chrome [4.0.2]

### ISSUE THREAD

**Issue by lead0r** [koekeishiya/kwm#539]
When I watch Youtube videos in fullscreen and then close the fullscreen, Chrome sometimes freezes and the rest of my screen goes black/I cannot use any program until I force chrome to close.

This does not always happen and I noticed it happens more often when I watch longer videos or when I close and enter fullscreen multiple times.

I use macOS Sierra 10.12.1.

**Comment by dominiklohmann** [comment]
Might be related to #524. Do you have window borders enabled? If so, does this also happen with windows borders disabled?

**Comment by dominiklohmann** [comment]
I think the patch has already been applied to the master branch (PR #527), just clone the repo and compile from source. 

You will have to re-enable accessibility permissions every time you compile unless you sign the binary using `codesign`, but that's not really an issue in my opinion.

The alternative is to wait for @koekeishiya to update the binary release.

**Comment by lead0r** [comment]
Alright, thanks for your help!

**Comment by lead0r** [comment]
Okay, unfortunately I have to say that the issue persisted even with borders disabled

**Comment by koekeishiya** [comment]
I have no input really on this yet, I have (unfortunately) no plans on updating my system to Sierra.

**Comment by arknave** [comment]
Also happens on netflix FWIW.

**Comment by choco** [comment]
As @dominiklohmann said this should be fixed on master, just compile yourselves or wait for a new binary release.

**Comment by lead0r** [comment]
Are you sure? As I stated, the problem still occurs even with borders disabled

**Comment by lead0r** [comment]
I am still not using borders, but after updating I think I have not experienced the problem again. Thanks!
